### ISSUE TITLE
MEG v0.95 - Checklist.xlsx - No.71

### ISSUE THREAD

**Issue by tsubasaxZZZ** [Azure/migration#5]
- MEG v0.95 - Checklist.xlsx - No.71

I'm not sure how to interpret it because the parentheses are mismatched.
```
Determine the digital estate planning approach - Workload based Top Down Assessment Approach -App aligned-5Rs IaaS/PaaS/SaaS) vs Asset-driven Approach (IaaS)
```

Is the following correct?
```
Determine the digital estate planning approach - Workload based Top Down Assessment Approach(App aligned-5Rs IaaS/PaaS/SaaS) vs Asset-driven Approach (IaaS)
```

And it would be easier for users to understand if it explain more in the "Description" column.

**Comment by Kaspanitz** [comment]
@tsubasaxZZZ I've updated the item title and added a description. Let me know if this will suffice.

**Comment by tsubasaxZZZ** [comment]
Thank you for updating Description!
